### ISSUE TITLE
dispatch_refresh

### ISSUE THREAD

**Issue by marc2k3** [kbuffington/foo_enhanced_playcount#1]
I saw some comments on the foobar forums about how many times on_metadb_changed was called in scripting panels and and then looked at your code... you shouldn't be calling dispatch_refresh inside a loop on a per hash basis. I even noted this in the docs for my metadb_index_client implemtenation for JScript Panel. 

https://github.com/marc2k3/foo_jscript_panel/wiki/Playback-Stats

It's not just bad for scripts but any library viewer/playlist views in your layout.

It can be done on many hashes at once when the loop is complete. Old code from PlayedTimes.cpp

```cpp
for (size_t t = 0; t < items.get_count(); t++) {
	metadb_index_hash hash;
	clientByGUID(guid_foo_enhanced_playcount_index)->hashHandle(items[t], hash);

	record_t record = getRecord(hash);
	record.lastfmPlaytimes.clear();
	record.numLastfmPlays = 0;
	setRecord(hash, record);
	theAPI()->dispatch_refresh(guid_foo_enhanced_playcount_index, hash);
}
```

Updated code...

```cpp
pfc::avltree_t<metadb_index_hash> tmp;

for (size_t t = 0; t < items.get_count(); t++) {
	metadb_index_hash hash;
	clientByGUID(guid_foo_enhanced_playcount_index)->hashHandle(items[t], hash);

	record_t record = getRecord(hash);
	record.lastfmPlaytimes.clear();
	record.numLastfmPlays = 0;
	setRecord(hash, record);
	tmp += hash;
}

pfc::list_t<metadb_index_hash> hashes;
for (auto iter = tmp.first(); iter.is_valid(); ++iter)
{
	const metadb_index_hash hash = *iter;
	hashes += hash;
}

theAPI()->dispatch_refresh(guid_foo_enhanced_playcount_index, hashes);
```

You'd also need to update the bit of code that calls the main thread callback as well - when the loop is complete.

**Comment by kbuffington** [comment]
This is an awesome suggestion. Will definitely be implementing this in the new version. Thanks!

**Comment by marc2k3** [comment]
Regarding the recent last.fm comments in your thread, you could remind the peasants that full functionality to import loved tracks, store the values in database and then loving/unloving tracks dependent on the current value is already supported in JScript Panel so long as they are on version 2 or later. It's explained here inside the `Last.fm Lover.txt` script here...

https://github.com/marc2k3/foo_jscript_panel/blob/63a2827636d0d36acb4384cf8d5711c25dbbdc15/foo_jscript_panel/samples/complete/last.fm%20lover.txt#L10L20

**Comment by marc2k3** [comment]
So I noticed this is using an undocumented presumably new Last.fm API...  `user.getTrackScrobbles`. Have you got any more of those tucked away up your sleeve? :grin:

**Comment by kbuffington** [comment]
Haha, didn't realize that method was still undocumented. A last.fm dev contacted me directly and told me that I had to switch to it as the current method I was using was being deprecated. Unfortunately I'll lose functionality, and responses are slower, but at least it'll keep working going forward.
