### ISSUE TITLE
Exact names of recommended panels

### ISSUE THREAD

**Issue by Korb** [kbuffington/foo_enhanced_playcount#8]
> you'll need to use one of the javascript panels such as Spider Monkey, JScript, or WSHPanel

https://www.foobar2000.org/components/view/foo_enhanced_playcount

> you'll need to use a panel that supports javascript, like foo_jscript_panel, or foo_wsh_panel.

https://wiki.hydrogenaud.io/index.php?title=Foobar2000:Components_1.0/foo_enhanced_playcount

I found the mention of [Spider Monkey Panel](https://www.foobar2000.org/components/view/foo_spider_monkey_panel) 1.6.1 (2022-01-13) in the list of components for foobar2000. However, it doesn't mention any of the others you listed: foo_jscript_panel, foo_wsh_panel, JScript, and WSHPanel. Maybe they are there under other names. Could you clarify this in the accompanying documentation?

**Comment by kbuffington** [comment]
The other components are not in the components registry. I now only recommend using either Spider Monkey which you linked above, or marc2k3's [jscript panel 3](https://jscript-panel.github.io/docs/).
